#!/bin/bash
heroku config:add JAVA_OPTS='-Xdebug -Xrunjdwp:transport=dt_socket,address=blah.domain.com:9999 -Xms512M -Xmx1024M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M -XX:+UseCompressedOops'
heroku restart
